ClickHouse: Array column read error
ydb-platform/fq-connector-go pull request #126
Opened 2024-06-10 14:16 UTC by lifthelm

2024-06-10 14:23 UTC, vitalyisaev2 requested changes

2024-06-10 14:23 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/clickhouse/type_mapper.go
> +	array := false
линтер дело говорит

2024-06-10 14:23 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/clickhouse/type_mapper.go
> +	// TODO: nullable array can not exist
Не хочется это откладывать в другие тикеты, м. б. сразу фиксить?

2024-06-10 14:23 UTC, vitalyisaev2 commented on tests/infra/datasource/clickhouse/tables.go
>  }
Давай напишем сразу тестик прямо здесь, в Go. Сценарий простой: дана таблица с неподдерживаемыми типами. Делаем `DescribeTable`, в схеме возвращаются столбцы только поддерживаемых типов. На этом всё, данные читать не нужно.

2024-06-11 15:52 UTC, vitalyisaev2 approved these changes

2024-06-11 15:53 UTC, vitalyisaev2 requested changes

2024-06-11 15:53 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/clickhouse/type_mapper.go
> +	if matches := tm.isArray.FindStringSubmatch(typeName); len(matches) > 0 {
здесь условие if не отличается от предыдущего... точно ли всё правильно? может, их можно объединить?

2024-06-11 15:58 UTC, vitalyisaev2 requested changes

2024-06-11 15:58 UTC, vitalyisaev2 commented on common/ydb_type_helpers.go
> +}
Эта функция сейчас используется? кмк, не должна - ведь мы не отдаем в метаданных таких колонок

2024-06-11 16:01 UTC, lifthelm commented on common/ydb_type_helpers.go
> +}
Используется для задания схемы таблицы с массивами в тестах
tests/infra/datasource/clickhouse/tables.go

2024-06-11 16:19 UTC, lifthelm commented on app/server/datasource/rdbms/clickhouse/type_mapper.go
> +	if matches := tm.isArray.FindStringSubmatch(typeName); len(matches) > 0 {
Зарефакторил

2024-06-11 16:29 UTC, vitalyisaev2 approved these changes

2024-06-11 16:30 UTC, merged