Adding Oracle datasource: go-ora/v2
ydb-platform/fq-connector-go pull request #148
Opened 2024-07-16 11:10 UTC by lifthelm

Adding Oracle datasource using go-ora/v2 with minimal type support: NUMBER(p,0) p > 0, p < Const to int64; VARHCAHR2, VARCHAR, NCHAR to string.

2024-07-16 13:39 UTC, vitalyisaev2 requested changes

2024-07-16 13:39 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/connection.go
> +	rows, err := NewRows(out)
давай заприватим, снаружи пакета функция эта не нужна

2024-07-16 13:39 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +	connStr1 := go_ora.BuildUrl(
просто `connStr`

2024-07-16 13:39 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +	)
А что у нас с TLS?

2024-07-16 13:39 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +	err = conn.Open()
используй `OpenWithContext` и прокинь туда контекст с таймаутом (по аналогии с ping)

2024-07-16 13:39 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +		defer conn.Close()
этот defer надо перенести выше пинга, здесь он не имеет смысла

2024-07-16 14:00 UTC, vitalyisaev2 requested changes

2024-07-16 14:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +			r.err = fmt.Errorf("oracle can't get next row calues: %w", err)
calues?

2024-07-16 14:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +	err := r.rows.Next(r.nextValuesBuffer)
перед этой строчкой просится проверка `inputFinished`

2024-07-16 14:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +	errUnsupportedType = errors.New("unsupported source type")
У нас уже есть такая ошибка, воспользуйся ей: https://github.com/ydb-platform/fq-connector-go/blob/main/common/errors.go#L26

2024-07-16 14:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +	// switch s := src.(type) {
выглядит не очень актуальным комментарием )

2024-07-16 14:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +	// TODO pass column type names and make type mapping
Это актуально? не совсем понимаю, для чего это нужно делать в этой функции

2024-07-16 14:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +		}
Если честно, я бы убрал в этих местах проверку на пустоту 
`		if d == nil {
			return errNilPtr
		}`
		
В таком коде экономия лишней инструкции CPU может иметь большое значение. Пусть лучше код упадёт - ведь это явно будет свидетельствовать о программистской ошибке.

2024-07-16 14:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +		i, err := strconv.Atoi(s)
Обсудили, что руками лучше не приводить строки к числам. Лучше переиспользовать структуры, предлагаемые go_ora

2024-07-16 15:24 UTC, vitalyisaev2 requested changes

2024-07-16 15:24 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/table_metadata_query.go
> +	// TODO: check synonyms tables and tables from other schemes
Если есть понимание, какой именно функциональности не хватает, давай лучше заводить тикеты с чуть более подробным описанием, потому что так пока не очень понятно. То же самое касатеся TODO строчкой выше.

2024-07-16 15:24 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +			acceptors = append(acceptors, new(*string))
Кажется, для этих типов они специально придумали https://github.com/sijms/go-ora/blob/v2.8.19/v2/custom_types.go#L73

2024-07-16 15:24 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +func transformerFromSQLTypes(types []string, ydbTypes []*Ydb.Type, cc conversion.Collection) (paging.RowTransformer[any], error) {
Касательно `types []string` - вот этот enum нигде в метаданных не фигурирует? https://github.com/sijms/go-ora/blob/master/parameter.go#L30-L77. Выглядит более эффективной заменой строк.

2024-07-16 15:24 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +		return nil
Не понял, как обрабатывается случай, что пришёл `nil`. Мы же должны по указателю в acceptor `nil` записать, разве нет?

2024-07-16 15:24 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +	*cast = nil
Мне кажется, что это присваивание должно быть не здесь. Это зона ответственности Scan'а, а не appender'а

2024-07-17 01:05 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/rows.go
> +func (*rows) NextResultSet() bool { return false }
Пока не до конца уверен в том что все данные возвращаются в одном result set

Похоже go-ora сама занимается управлением prefetch без NextResultSet
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/command.go#L2245
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/command.go#L2216
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/command.go#L2261

https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/data_set.go#L115-L116
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/data_set.go#L300-L353

driver.Rows не имеет NextResultSet, но его можно привести к другому типу, который имеет NextResultSet
https://pkg.go.dev/database/sql/driver#Rows
https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/database/sql/sql.go;drc=0d018b49e33b1383dc0ae5cc968e800dffeeaf7d;l=3096
https://cs.opensource.google/go/go/+/master:src/database/sql/driver/driver.go;drc=08a6e080cae0277f0c5458da84c7e3ca4d8f8199;l=447

2024-07-17 19:48 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/rows.go
> +		i, err := strconv.Atoi(s)
Повторно обсудили и исследовали, пришли к тому, чтобы использовать strconv.Atoi

2024-07-17 22:44 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +		defer conn.Close()
Не понял куда стоит перенесли defer с закрытием соединения. Возможно само соединение открывать с контекстом запроса?

2024-07-18 02:13 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +	)
Для TLS/SSL требуется некоторый wallet, в котором хранятся сертификаты
https://oracle-base.com/articles/misc/configure-tcpip-with-ssl-and-tls-for-database-connections
https://stackoverflow.com/questions/78164683/handling-certificates-for-establishing-connection-to-oracle-using-the-go-ora-dri

2024-07-18 02:21 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +			acceptors = append(acceptors, new(*string))
NullNVARCHAR в последовательности вызова начинает использовать reflect
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/utils.go#L217-L230

2024-07-18 02:56 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +func transformerFromSQLTypes(types []string, ydbTypes []*Ydb.Type, cc conversion.Collection) (paging.RowTransformer[any], error) {
Похоже этот enum получится использовать, если удастся использовать go_ora.DataSet напрямую, а не driver.Rows. Есть гипотеза, что driver.Rows можно просто привести к go_ora.DataSet типу.
Данный enum из первой версии go_ora. В версии v2 используется TNSType

Использование DataType из колонки DataSet
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/data_set.go#L397-L409
Тип колонки DataSet - массив ParameterInfo
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/data_set.go#L34
ParameterInfo
В ParameterInfo DataType имеет тип TNSType
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/parameter.go#L118
TNSType - enum - полный аналог OracleType
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/parameter.go#L46-L98

2024-07-18 12:02 UTC, vitalyisaev2 requested changes

2024-07-18 14:42 UTC, vitalyisaev2 requested changes

2024-07-18 14:42 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +		return scanNilToDest(dest)
Если в базе был `NULL`, то мы точно попадём в этот case? вставь дебаг принты и давай проверим

2024-07-18 14:42 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +	case string:
что делать, если пришла пустая строка? это нарушение инварианта (т. е. так не бывает) или это пустое значение?

2024-07-18 14:51 UTC, vitalyisaev2 requested changes

2024-07-18 14:51 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +	case string:
как мы будем конвертировать пустую строку в int?

2024-07-18 14:51 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +func transformerFromSQLTypes(types []string, ydbTypes []*Ydb.Type, cc conversion.Collection) (paging.RowTransformer[any], error) {
Ну да - хорошо бы вытащить `TNSType`  (кстати, что такое TNS?) или `OracleType` к нам.

2024-07-18 14:51 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +			acceptors = append(acceptors, new(*string))
ок, если мы без рефлекта обошлись, то пусть будет так

2024-07-18 15:28 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +	)
Будет выполнено в другом PR

2024-07-18 15:28 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +		defer conn.Close()
Обсудили устно, пришли к тому, что надо просто убрать defer перел conn.Close()

2024-07-18 15:30 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/connection_manager.go
> +	err = conn.OpenWithContext(ctx)
Обсудили устно, пришли к тому, что в сейчас реализовано корректно

2024-07-18 19:36 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/type_mapper.go
> +func transformerFromSQLTypes(types []string, ydbTypes []*Ydb.Type, cc conversion.Collection) (paging.RowTransformer[any], error) {
Обсудили, пришли к выводу, что не получится использовать TNSType

2024-07-19 18:09 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/rows.go
> +func (*rows) NextResultSet() bool { return false }
Пришел к выводу, что в go-ora v2 не реализовано driver.RowsNextResultSet.
В go-ora v2 структура DataSet интерфейс driver.Rows. И у данной структуры отсутсвуют необходимые методы для реализации driver.RowsNextResultSet, который содержит метод NextResultSet.
Для подтверждения этого провел тест с приведением driver.Rows, приходящих с conn.QeuryContext, с приведением к типу driver.RowsNextResultSet, по аналогии из стандартной библиотеки:
```go
nextResultSet, ok := rs.rowsi.(driver.RowsNextResultSet)
if !ok {
  doClose = true
  return false
}
```
Также детально изучил реализацию библиотеки и пришел к выводу, что в методе Next каждый раз происходит fetch строк кода с соединения с базой данных, до окончания данных.
Именно DataSet возвращается в качестве driver.Rows исходя из исходников библиотеки.

DataSet:
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/data_set.go#L28-L40
Next:
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/data_set.go#L300-L353

2024-07-19 18:37 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/rows.go
> +		return scanNilToDest(dest)
В случае, если в базе был `NULL`, то в scan приходит нетипизированный `nil`:

```go
fmt.Printf("got source %+v (%T) to dest (%T)\n", src, src, dest)
```
```
got source someStr (string) to dest (**string)
RowsScan: scanning 5
got source -123 (string) to dest (**int64)
RowsScan: scanning 1
got source 4 (string) to dest (**int64)
RowsScan: scanning 2
got source <nil> (<nil>) to dest (**int64)
got nil to dest **int64
RowsScan: scanning 3
got source <nil> (<nil>) to dest (**string)
```

2024-07-19 18:45 UTC, lifthelm commented on app/server/datasource/rdbms/oracle/rows.go
> +	case string:
В случае с NUMBER протестировал для значения 0, >0, <0, Int64Max, во всех случая приходит строка (0 -> "0"). В случае с VARCHAR2 пустая строка невозможно, похоже  Oracle внутренне интерпретирует или приводит все пустые строки к NULL.

2024-07-20 08:41 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +func (*rows) NextResultSet() bool { return false }
спасибо

2024-07-20 08:44 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/oracle/rows.go
> +	case string:
Какая удобная база. Надо нам не забыть, что `VARCHAR2` имеет такую "удобную" особенность.

2024-07-20 08:46 UTC, merged