Mongodb: proposal.md draft
ydb-platform/fq-connector-go pull request #206
Opened 2024-10-18 07:10 UTC by ninaiad

2024-10-22 08:16 UTC, vitalyisaev2 requested changes

2024-10-22 08:16 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +- [DocDB - Arrow](https://docs.aws.amazon.com/athena/latest/ug/connectors-docdb.html#connectors-docdb-data-type-support)
Очень странно - здесь флоаты как раз есть? а в Trino нет?

2024-10-22 08:16 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +- Чтение схемы из специальной коллекции в бд MongoDB, которую создал пользователь, или дополнительного конфигурационного файла
Спасибо за декомпозицию. У меня такое ощущение, что мы пока можем без этого обойтись просто потому, что вот эти дополнительные параметры (специальную коллекцию или доп. файл будет нелегко прокинуть через YDB). Мне кажется более правильным начать с вывода схемы на лету. 

Предлагаю для начала написать библиотечку по трансформации JSON или BSON документа (или N документов, потоково) в схему YDB. Покрыть тестами, посмотреть на узкие места.

2024-10-22 08:16 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +- Извлечение схемы + type inference с помощью маленького скана коллекции с возможностью редактирования
я предлагаю это перенести наверх (сразу после слова minimum)

2024-10-22 08:16 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +ержка чтения схемы из систем вроде Apache Hive Metastore
Лишний перенос строки.

2024-10-22 13:41 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +- `SELECT * FROM ... ` без предикатов в коллекции с гомогенными документами
Давай распишем более подробно: пример документа, пример селекта из него, и пример ответа от федеративной базы данных. В особенности интересно, как Trino и другие движки работают с документами с вложенностью. Желательно экспериментально это проверить.

2024-10-22 16:04 UTC, ninaiad commented on app/server/datasource/mongodb/proposal.md
> +|`DBRef`|`ROW`||
2.  Есть Double как в BSON, он в списке после Int64

2024-10-22 16:26 UTC, ninaiad commented on app/server/datasource/mongodb/proposal.md
> +- [DocDB - Arrow](https://docs.aws.amazon.com/athena/latest/ug/connectors-docdb.html#connectors-docdb-data-type-support)
В DocumentDB используются JSON number в качестве чисел с плавающей точкой, что на практике должно быть идентично Double из MongoDB

2024-11-07 06:46 UTC, vitalyisaev2 requested changes

2024-11-07 06:46 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +- Доп. способ: чтение схемы из [AWS Glue](https://docs.aws.amazon.com/athena/latest/ug/connectors-docdb.html#connectors-docdb-setting-up-databases-and-tables-in-aws-glue)
То есть в отличие от Trino Athena не занимается складыванием схемы обратно в Mongo?

2024-11-07 06:46 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +- Чтение схемы из специальной коллекции в бд MongoDB, которую создал пользователь, или дополнительного конфигурационного файла
Перенеси плз этот пункт вниз, в продвинутую реализацию

2024-11-07 06:46 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +|    42 | 2.14748365E9 | outer   | [1, 2, 3] |   1.23 | 2020-05-18 14:10:30.000 | true    | 9823.1297 | {int32=13, str=inner}
Я вот не совсем понял, в колонке `Object` что это за сериализация такая? Это как бы и не JSON, и не строка... что ты такое?.. Не оч понятно, что нам возвращать - строку с JSONом?

2024-11-07 09:45 UTC, ninaiad commented on app/server/datasource/mongodb/proposal.md
> +      type: 'row("inner" row("field" bigint))',
Это нативная сериализация MongoDB, она так выглядит и в драйверах и в mongosh при запросах в бд и выводе документов в консоль. Перенимать ее не нужно, просто так выглядит представление json-подобных документов в монго.

2024-11-07 09:47 UTC, ninaiad commented on app/server/datasource/mongodb/proposal.md
> +- Доп. способ: чтение схемы из [AWS Glue](https://docs.aws.amazon.com/athena/latest/ug/connectors-docdb.html#connectors-docdb-setting-up-databases-and-tables-in-aws-glue)
Athena, насколько я поняла, вообще не поддерживает запись в MongoDB, и схему, да, никак сама персистентно не сохраняет (если ее уже не ввели вручную в AWS Glue).

2024-11-07 10:19 UTC, vitalyisaev2 commented on app/server/datasource/mongodb/proposal.md
> +- Доп. способ: чтение схемы из [AWS Glue](https://docs.aws.amazon.com/athena/latest/ug/connectors-docdb.html#connectors-docdb-setting-up-databases-and-tables-in-aws-glue)
вот и нам надо так же на первых порах

2024-11-07 10:19 UTC, merged