YQ-2609: version information feature
ydb-platform/fq-connector-go pull request #3
Opened 2023-12-19 09:36 UTC by Woodey777

2023-12-19 12:25 UTC, Woodey777 commented on app/main.go
> +	//go:embed VERSION.txt
без этого файла не работает ci
может добавить его пустым? или изменить ci тогда чтобы делался go generate сначала?

2023-12-19 12:26 UTC, Woodey777 commented on app/main.go
> +		if (showVersion == true) {
если стоит флаг -v то выводим строку
иначе выводим хелп

2023-12-19 12:27 UTC, Woodey777 commented on app/main.go
> +	rootCmd.Flags().BoolVarP(&showVersion, "version", "v", false, "show current version")
добавление флага -v и привязка к нему переменной

2023-12-19 14:03 UTC, Woodey777 commented on app/version.sh
> +TAG=$(git describe --tags)
в случае если тег находится не на текущем коммите, то пока получение длинного тега с мусором(v0.0.6-rc.7-7-g99072c3 напр)

2023-12-19 14:07 UTC, Woodey777 commented on app/version.sh
> +BUILD_LOCATION=$(pwd)
pwd работает, если бинарник будет собран там же, где и main.go лежит
если будет ```go build -o ../fq-connector```
, то не сработает, конечно

2023-12-19 14:09 UTC, Woodey777 commented on app/version.sh
> +HOSTINFO="$(uname -s) $(hostname) $(uname -r) $(date) $(uname -m)"
в оригинале это
```Linux onetime-ydb-agent-855382 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64```
у нас 
```Linux mr-nvme-testing-01.search.yandex.net 5.4.161-26.3 Tue 19 Dec 2023 02:02:48 PM UTC x86_64```

что такое "5.4.0-166-generic #183-Ubuntu SMP"?

2023-12-20 14:27 UTC, Woodey777 commented on app/main.go
> +		if showVersion {
если есть флаг, то принт
иначе хелп

2023-12-20 16:49 UTC, vitalyisaev2 requested changes

2023-12-20 16:49 UTC, vitalyisaev2 commented on app/build.sh
> +
Сделай, пожалуйста, bash скрипт, который будет выдавать эту строку. Можно назвать его, например, `./git_version_ldflags.sh` или как-то ещё. Положить его можно в корне репозитория.

На CI мы будем пользоваться им приблизительно так:
```
go build -ldflags "($ ./git_version_ldflags.sh)" ./app
```

2023-12-20 16:49 UTC, vitalyisaev2 commented on app/buildinfo/buildinfo.go
> +	info := fmt.Sprintln("Git info:")
давай сделаем конкатенацию строк через `strings.Builder` https://zetcode.com/golang/builder/

2023-12-20 16:49 UTC, vitalyisaev2 commented on app/main.go
> +		if showVersion {
Лучше это сделать через сабкомманды. У нас сейчас две комманды - `client`, `server`. Должна получиться третья - `version`.

2023-12-22 08:16 UTC, vitalyisaev2 requested changes

2023-12-22 08:16 UTC, vitalyisaev2 commented on app/get_ldflags.sh
> +
давай пока этот скрипт на верхний уровень репозитория переместим

2023-12-22 08:16 UTC, vitalyisaev2 commented on app/main.go
> +	// Run: func(cmd *cobra.Command, args []string)
этот код не нужен?

2023-12-22 08:16 UTC, vitalyisaev2 commented on app/version/version.go
> +	sb.WriteString(fmt.Sprintf("	Branch: %s\n", Branch))
отступы лучше делать табами `\t`

2023-12-22 11:35 UTC, vitalyisaev2 approved these changes

2023-12-22 11:35 UTC, merged