YQ-2794: Support datetime types for ydb
ydb-platform/fq-connector-go pull request #33
Opened 2024-01-19 11:03 UTC by tsmax2004

2024-01-19 12:59 UTC, vitalyisaev2 submitted a review, later dismissed

2024-01-22 12:07 UTC, vitalyisaev2 requested changes

2024-01-24 10:01 UTC, tsmax2004 commented on tests/infra/datasource/matching.go
> +	Columns map[string]any
done

2024-01-24 10:24 UTC, vitalyisaev2 approved these changes

2024-01-24 10:25 UTC, merged