*add auto change to ydb
ydb-platform/fq-connector-go pull request #80
Opened 2024-04-18 16:54 UTC by skywalker-jpg

2024-04-19 07:22 UTC, vitalyisaev2 requested changes

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	cmd := exec.Command("curl", link)
Вообще использование внешних бинарников при программировании на Go - это чаще всего индикатор костылей. В данном случае не вижу причин иметь зависимость на `curl`, лучше использовать  обычный `http.Client`

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	json.Unmarshal(output, &releases)
Где проверка ошибок?

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +func check_path(path string) bool {
1. название функции должно быть в camel case
2. непонятно, что данная функция делает, что значит `check`? нужно попонятнее название. Когда будет понятно назначение функции, возможно, потребуются исправления в логике. Ошибки в 99% случаев игнорить нельзя

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +			composeFilePath := filepath.Join(path, "docker-compose.yml")
Там часто бывает путаница - либо `docker-compose.yml`, либо `docker-compose.yaml`. Надо это учесть (если хочешь, напиши регулярку, либо как-то ещё).

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +				changeDockerCompose(composeFilePath, newImage)
Где проверка ошибок?

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +			if _, err := os.Stat(composeFilePath); err == nil {
ты же написал отдельную функцию для проверки файлов, разве нет?

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		return err
враппинг ошибок

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		return err
враппинг ошибок

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		if strings.Contains(line, "image:") {
Ты так перезатрёшь все строки, начинающиеся с `image:`. Так делать не надо, потому что их там много, а нужно править только ту, которая относится к сервису Коннектора. Используй библиотеку для работы c YAML. Десериализуй файл из YAML, внеси изменения, затем сериализуй обратно и сохрани в файл.

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	err = os.WriteFile("docker-file.yml", []byte(strings.Join(lines, "\n")), 0644)
у тебя же есть переменная path

2024-04-19 07:22 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	fmt.Printf("Updated %s\n", path)
Когда хочешь что-то напечатать, используй библиотеку для логирования. В коннекторе используется `zap.Logger`. Можешь создать экземпляр для начала вот так https://github.com/ydb-platform/fq-connector-go/blob/main/common/logger.go#L64, а затем протащить его во все функции.

2024-04-19 07:34 UTC, vitalyisaev2 requested changes

2024-04-19 07:34 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +const path_to_composes = "/ydb/library/yql/providers/generic/connector/tests/datasource"
1. не используй `snake_case` в коде на Go
2. придумай другую структуру данных, у нас таких путей будет несколько
* `/ydb/library/yql/providers/generic/connector/tests/` - здесь подпапки `datasource` и `join`
* `/ydb/tests/fq/generic`

2024-04-19 07:34 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +}
Не совсем понял, эта структура данных в итоге нужна или нет? если нужна, она должна быть объявлена скорее не в `main.go`, а ближе к коду, где она используется.

2024-04-19 07:34 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +	checksum := flag.String("checksum", "checksum", "Specify checksum.")
Если других предложений не будет, я предлагаю закостылить извлечение чексуммы тем способом, что я предложил вчера. Просто встроенным HTTP Client'ом качаешь страничку, соответствующую тегу, и находишь там нужную строчку. По итогу этот параметр должен уйти.

2024-04-19 07:34 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +		return nil
Ошибки печатать надо в каком-то одном месте. У тебя есть для этого функция main. Поэтому вместо того, чтобы печатать что-то в консоль, просто верни ошибку: `return fmt.Errorf("Path does not exist")`.

Но вообще мне не особо нравится сигнатура функции `check_path`. Я бы оттуда вернул ошибку.

2024-04-19 07:34 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +	tag, err := getVersion()
переименуй в `getLatestVersion` или как-то ещё, чтобы было понятно, что происходит

2024-04-19 07:37 UTC, vitalyisaev2 commented on go.mod
> +	github.com/google/go-github/v61 v61.0.0 // indirect
кстати, по итогу не увидел использования этой либы в коде

2024-04-19 08:02 UTC, skywalker-jpg commented on go.mod
> +	github.com/google/go-github/v61 v61.0.0 // indirect
да, в итоге оказалась не нужна

2024-04-19 08:24 UTC, skywalker-jpg commented on tools/dc_update/internal.go
> +		return "", err
те в ошибки писать какая функция их вызвала и саму ошибку?

2024-04-19 08:28 UTC, skywalker-jpg commented on tools/dc_update/main.go
> +const path_to_composes = "/ydb/library/yql/providers/generic/connector/tests/datasource"
не очень понял насчет второго пункта

2024-04-19 09:08 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +const path_to_composes = "/ydb/library/yql/providers/generic/connector/tests/datasource"
Файлы docker-compose.yml расположены в нескольких папках репозитория YDB.

2024-04-19 09:08 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		return "", err
да. поправил свой предыдущий комментарий, теперь должно стать понятнее

2024-04-19 10:25 UTC, vitalyisaev2 requested changes

2024-04-19 10:25 UTC, vitalyisaev2 commented on go.sum
> +github.com/google/go-github/v61 v61.0.0 h1:VwQCBwhyE9JclCI+22/7mLB1PuU9eowCXKY5pNlu1go=
всё ещё остались лишние строки от неиспользуемой либы

2024-04-19 10:25 UTC, vitalyisaev2 commented on README.md
> +...
![image](https://github.com/ydb-platform/fq-connector-go/assets/5507054/b6eaae1b-f02f-4de2-b377-1f948d1b4149)

2024-04-19 10:25 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +type Release struct {
Надо очень внимательно относиться к тому, какое API мы публикуем. Это публичный тип, он должен использоваться вне этого пакета? Нет? Тогда с маленькой буквы.

2024-04-19 10:25 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	req, err := http.NewRequest("GET", link, nil)
`link` это глобальная переменная? Объяви её поближе к месту использования, а то с таким неймингом вообще непонятно, для чего она нужна. А ещё лучше помести прям в эту функцию.

2024-04-19 10:25 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	resp, err := client.Do(req)
Добавь к запросу контекст (`context.WithTimeout` с каким-то разумным таймаутом), чтобы эта функция не заблокировалась навечно из-за проблем с сетью.

2024-04-19 10:25 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	link := fmt.Sprintf("https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go/204229242?tag=%s", tag)
1. Что означает `204229242`? почему оно захардкожено?
2. Для конструирования URL c параметрами лучше использовать структурированный подход (т. е. через `url.URL{}`)

2024-04-19 10:25 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	lines := strings.Split(string(body), "\n")
Здесь несколько неоптимальных моментов:

1. Полностью вычитывается весь ответ в переменную `body`. Хотя вся страница нам не нужна. Нужна только первая (вроде) строка с префиксом `sha256`).
2. Дальше вся вычитанная страница разбивается на строки, которые тоже нам все не нужны. То есть мы используем 3x памяти, да и процессор тратим на разбиение.
3. В цикле по строкам ты итерируешься до конца, хотя тебе нужна только одна строка.

Вместо этого всего попробуй использовать потоковый подход. Вычитывай из буфера строчку за строчкой, затем прекращай чтение. 

https://stackoverflow.com/questions/8757389/reading-a-file-line-by-line-in-go

2024-04-19 10:27 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +				changeDockerCompose(composeFilePath, newImage)
не ресолвь замечания, если ты их не поправил

2024-04-19 10:59 UTC, skywalker-jpg commented on README.md
> +...
это с первого пробного коммита осталось(((

2024-04-19 11:17 UTC, vitalyisaev2 requested changes

2024-04-19 11:17 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +func changeDockerCompose(path string, newImage string) error {
Напиши интеграционный тестик на эту функцию. Дан файл `docker-compose.yaml` - за образец можно взять один из наших файлов, расположенных в репозитории YDB. Сценарий теста:
1. Создаём во временной папке файл с указанным содержанием
2. Натравливаем на него нашу функцию
3. Считываем файл и проверяем, что он поменялся так, как нам надо
4. Удаляем за собой файл

2024-04-19 11:17 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		if strings.Contains(line, "image:") {
Здесь работа должна выполняться через YAML. 

PS. Не ресолвь замечания, если ты их не поправил ))

2024-04-19 11:17 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	fmt.Printf("Updated %s\n", path)
Не  ресолвь замечания, если ты их не поправил.

2024-04-19 11:17 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	log.Printf("Updated %s\n", path)
У нас используется не глобальный логгер из стдлибы Go, а `*zap.Logger`. Тебе нужно проинициализировать его в main, и прокинуть во все места, где ты им будешь пользоваться. В другом замечании я писал, где взять конструктор для логгера.

2024-04-19 11:17 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +		return err
Везде нужен враппинг ошибок. Если враппинг не сделан, потом очень долго можно разбираться по коду, где она произошла.

2024-04-19 11:25 UTC, skywalker-jpg commented on tools/dc_update/internal.go
> +		if strings.Contains(line, "image:") {
но у меня не получится все yaml в одинаковую структуру считать+в разных ямах это вроде по разному называется, где-то connector, где то fq-connector-go. я у себя сделал по-другому чуть-чуть, сейчас покажу

2024-04-19 11:29 UTC, skywalker-jpg commented on tools/dc_update/internal.go
> +func changeDockerCompose(path string, newImage string) error {
все рабит))

2024-04-19 11:31 UTC, skywalker-jpg commented on tools/dc_update/internal.go
> +	log.Printf("Updated %s\n", path)
да, я просто подумал что именно зап не обязательно, ибо в соседнем ydbinit он не используется и все делается через обычный логгер

2024-04-19 13:12 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		if strings.Contains(line, "image:") {
Не поленился пройтись по всем docker-compose файлам, везде `fq-connector-go`:

https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/connector/tests/join/docker-compose.yml
https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/docker-compose.yml
https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/docker-compose.yml
https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/providers/generic/connector/tests/datasource/ydb/docker-compose.yml
https://github.com/ydb-platform/ydb/blob/main/ydb/tests/fq/generic/docker-compose.yml

2024-04-19 13:21 UTC, vitalyisaev2 requested changes

2024-04-19 13:21 UTC, vitalyisaev2 commented on docker-file.yaml
> +  connector:
У тебя немножко устаревшая версия. Возьми файл посвежее, там везде `fq-connector-go`. Ссылки я привёл в другом комментарии.

2024-04-19 13:21 UTC, vitalyisaev2 commented on docker-file.yaml
> +version: '3.4'
Давай назовём файл `docker-compose.yml` или как-то похоже, а то `docker-file` не очень понятное название

2024-04-19 13:56 UTC, vitalyisaev2 requested changes

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		}
Лишний if

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	baseLink := "https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go/204229242"
Уже не могу найти это замечание (видимо, опять закрыто)) - я хотел спросить, что такое `204229242`. Напиши плиз, что это такое в комментариях, пока выглядит как магическое число.

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		}
это тоже лишнее

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +		return "", fmt.Errorf("http newRequest: %w", err)
В этом ревью не критично, но на будущее лучше в префиксе с аннотацией ошибки использовать не `camelCase`, а обычное написание, то есть `"http new request: %w"`

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	for scanner.Scan() {
Предлагаю переписать построчную обработку текста на `dict['services']['fq-connector-go']['image']`. По крайней мере, попробовать.

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	err = os.WriteFile("docker-file.yaml", []byte(strings.Join(lines, "\n")), 0644)
захардкодил неправильное имя файла

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +func changeDockerCompose(path string, newImage string, logger *zap.Logger) error {
`logger` передаём всегда первым аргументом

если есть `context`, то `context` идёт первым, а `logger` - вторым

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	logger.Info("Updated", zap.Any("path", path))
`zap.String`

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +	path := flag.String("path", "path", "Specify the path to the file ydb file.")
"to the file ydb file" - это как-то не по-русски )

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +	logger.Info("values", zap.Any("path", path), zap.Any("tag", tag), zap.Any("checksum", checksum))
Старайся избегать `zap.Any`, не применять его без лишней нужды. В данном случае везде подойдёт `zap.String`.

2024-04-19 13:56 UTC, vitalyisaev2 commented on tools/dc_update/main.go
> +	log.Println(path, tag, checksum)
забыл удалить, наверное

2024-04-19 13:57 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +func changeDockerCompose(path string, newImage string) error {
Ну теперь попробуй обновить локальный форк ydb (пример команды: `gh repo sync vitalyisaev2/ydb -s ydb-platform/ydb`) и применить свой скрипт! Если всё нормально отработает, можешь прислать PR

2024-04-19 13:57 UTC, skywalker-jpg commented on tools/dc_update/internal.go
> +	baseLink := "https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go/204229242"
да, я думал комменты видно, я там ответил, что я не знаю, это со вчерашнего костыля

2024-04-19 14:25 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	baseLink := "https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go/204229242"
Это блокер для нас. Например, я хотел получить данные за предыдущий релиз, и вот что получилось

```
➜  ~ curl https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go/204229242\?tag\=v0.2.20 2>&1 | grep sha256 | head -n 1
          <code>sha256:a1771f348dc8be6219865e332f788429907cdfec3677b3e98f0bc6f7dd542dc6</code>
➜  ~ curl https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go/204229242\?tag\=v0.2.19 2>&1 | grep sha256 | head -n 1
          <span>sha256:a1771f348dc8be6219865e332f788429907cdfec3677b3e98f0bc6f7dd542dc6</span>
```

то есть выдалась чексумма не для v0.2.20, а для v0.2.19. Следовательно, `204229242` это какой-то параметр, и его нельзя хардкодить.

2024-04-19 14:26 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	baseLink := "https://github.com/ydb-platform/fq-connector-go/pkgs/container/fq-connector-go/204229242"
> да, я думал комменты видно, я там ответил

Если просто ответил, но не поправил - не закрывай комментарий, иначе я не смогу увидеть твой ответ.

2024-04-22 07:17 UTC, vitalyisaev2 requested changes

2024-04-22 07:17 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +			}
Если файла нет, давай вернём ошибку. Файл точно должен быть. Иначе нарушение инварианта

2024-04-22 07:17 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	"gopkg.in/yaml.v2"
Не увидел соответствующей записи в `go.mod`. `go mod tidy`?

2024-04-22 07:17 UTC, vitalyisaev2 commented on tools/dc_update/internal.go
> +	updatedYaml, err := yaml.Marshal(data)
там нет никаких опций маршалинга? Желательно, чтобы наш скрипт не слишком сильно менял файлы при каждом следующем вызове

2024-04-22 08:51 UTC, skywalker-jpg commented on tools/dc_update/internal.go
> +	updatedYaml, err := yaml.Marshal(data)
он их вроде не меняет, только image исправляет. остальное остается как было

2024-04-22 09:31 UTC, vitalyisaev2 requested changes

2024-04-22 09:31 UTC, vitalyisaev2 commented on Makefile
> +	go run ./tools/docker_compose_update -path="$(path)"
а что значит `path` - как это должно работать? откуда он берётся? путь до локальной копии YDB у каждого свой, разве нет?

Я потому и предлагал вызывать это как `./docker_compose_update /home/виталя/ydb` или `./docker_compose_update /home/timur/projects/ydb`

2024-04-22 09:31 UTC, vitalyisaev2 commented on tools/docker_compose_update/internal.go
> +		}
Здесь лучше прислушаться к линтеру, чтобы код стал чуть более читаемым

2024-04-22 09:34 UTC, skywalker-jpg commented on Makefile
> +	go run ./tools/docker_compose_update -path="$(path)"
оно вот такой командой запускается make docker_compose_update path=путь до файла ydb

2024-04-22 11:27 UTC, merged