YQ-2811 add Arc versions
ydb-platform/fq-connector-go pull request #92
Opened 2024-04-25 08:38 UTC by skywalker-jpg

2024-04-25 08:47 UTC, vitalyisaev2 requested changes

2024-04-25 08:47 UTC, vitalyisaev2 commented on tools/version/main.go
> +	var err error
старайся такие места объединять в блоки `var`

```
var (
    data versionData
    err error
)
```

2024-04-25 08:47 UTC, vitalyisaev2 commented on tools/version/main.go
> +	if len(os.Args) < 2 {
так может сразу написать правильно, что если `len(os.Args) != 2`, то ошибка?

2024-04-26 11:29 UTC, vitalyisaev2 requested changes

2024-04-26 11:29 UTC, vitalyisaev2 commented on tools/version/main.go
> +	if len(os.Args) < 2 {
а если будет больше 2? лучше запрещать всё, что не разрешено

2024-04-26 11:29 UTC, vitalyisaev2 commented on tools/version/main.go
> +	filepath := homeDir + "/arcadia/vendor/github.com/ydb-platform/fq-connector-go/.yo.snapshot.json"
Вот это сомнительное место, подозреваю, что не так оно должно работать. Критерий успеха такой. Вызываем команду:

```
ya package --docker ~/arcadia/kikimr/deployment/docker/yq-connector/pkg.json --docker-network=host
```

Локально появляется Docker образ. Заходим в него и там проверяем, какую информацию выдаёт команда `version`.

2024-04-26 11:29 UTC, vitalyisaev2 commented on tools/version/main.go
> +func getVersions() (string, string, error) {
1. плохой нейминг функции. у нас уже есть `getGitVersion` и `getArcVersion`, и внезапно какой-то `getVersions`, который делает что-то совсем другое
2. соглашусь с линтером - отсюда надо возвращать структуру, так не понятно, что за строки

2024-04-26 12:59 UTC, skywalker-jpg commented on tools/version/main.go
> +	filepath := homeDir + "/arcadia/vendor/github.com/ydb-platform/fq-connector-go/.yo.snapshot.json"
не пускает меня посмотреть базовый имадж. Попытался авторизироваться - не пускает

2024-04-26 13:49 UTC, vitalyisaev2 commented on tools/version/main.go
> +	filepath := homeDir + "/arcadia/vendor/github.com/ydb-platform/fq-connector-go/.yo.snapshot.json"
в общем завтра задача №1 нам настроить все доступы в облаке

2024-04-26 13:50 UTC, vitalyisaev2 commented on tools/version/main.go
> +	filepath := homeDir + "/arcadia/vendor/github.com/ydb-platform/fq-connector-go/.yo.snapshot.json"
пока с `ya make` тогда тренируйся, если заведётся - я из твоей ветки попробую образ собрать

2024-04-27 11:05 UTC, merged