Add MS SQL Server
ydb-platform/fq-connector-go pull request #93
Opened 2024-04-26 12:39 UTC by Glebbs

2024-04-26 12:59 UTC, vitalyisaev2 requested changes

2024-04-26 12:59 UTC, vitalyisaev2 commented on app/client/connector/client.go
> +	fmt.Println("-----------CLIENT-------------")
![image](https://github.com/ydb-platform/fq-connector-go/assets/5507054/a1ee12a4-218e-4e3c-9c8a-8baf1d98f9f5)

2024-04-26 12:59 UTC, vitalyisaev2 commented on app/server/data_source_collection.go
> +		fmt.Println("---------------DSS COLLECTION------------------")
![image](https://github.com/ydb-platform/fq-connector-go/assets/5507054/49c839d8-156f-464c-add6-a14fb1b9aa13)

2024-04-26 12:59 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/connection_manager.go
> +	fmt.Println("------------CONN MANAGER-------------------")
![image](https://github.com/ydb-platform/fq-connector-go/assets/5507054/677baff0-7069-455d-a9db-a038ce1af7ab)

2024-04-26 12:59 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/connection_manager.go
> +	fmt.Println("------------CONN MANAGER-------------------")
и это тоже удоли

2024-04-26 12:59 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/utils/schema_builder.go
> +	fmt.Println("-------------Schema Builder------------------")
все дебажные принты надо почистить

2024-04-26 14:27 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/connection.go
> +	out, err := c.db.Query(query, args...)
используй метод `QueryContext`, пробрось туда контекст, а `_ = ctx` после этого удалишь

2024-04-26 14:35 UTC, vitalyisaev2 requested changes

2024-04-26 15:12 UTC, vitalyisaev2 requested changes

2024-04-26 15:12 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +		ydbType, err = common.MakeYdbDateTimeType(Ydb.Type_TIMESTAMP, rules.GetDateTimeFormat())
Этот маппинг типов, связанных с датой и временем, явно неправильный - на стороне YDB не только таймстемп, но и другие типы есть. Если не знаешь, как сделать сейчас, или не успеваешь, лучше верни ошибку. В следующем PR доделаешь.

2024-04-26 15:12 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +		ydbType = common.MakePrimitiveType(Ydb.Type_DOUBLE)
42 и 44 строки точно не перепутал?

2024-04-26 15:12 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +	// Reference table: https://github.com/ydb-platform/fq-connector-go/blob/main/docs/type_mapping_table.md
укажи здесь же ссылку на доку по системе типов MS SQL Server. а то мне страшно от `datetime2`.

2024-04-26 15:12 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +			// ваш вызов преобразователя (appender)
а здесь в чём сложность? должно быть так же, как с `bytea` в PG, в моём понимании

2024-04-26 15:12 UTC, vitalyisaev2 commented on app/server/validate.go
> +		// }
```
// TODO: check schema
return nil
```

2024-04-26 16:34 UTC, Glebbs commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +	}
нет

2024-04-26 16:36 UTC, Glebbs commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +		ydbType = common.MakePrimitiveType(Ydb.Type_DOUBLE)
Все согласно размерности - 4 и 8 байт соответственно. 
https://learn.microsoft.com/ru-ru/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-ver16
https://ydb.tech/docs/ru/yql/reference/types/primitive

2024-04-26 16:39 UTC, Glebbs commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +		ydbType, err = common.MakeYdbDateTimeType(Ydb.Type_TIMESTAMP, rules.GetDateTimeFormat())
Пока верну ошибку

2024-04-26 17:20 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +		ydbType = common.MakePrimitiveType(Ydb.Type_DOUBLE)
мда...

2024-04-26 20:55 UTC, Glebbs commented on app/server/datasource/rdbms/ms_sql_server/connection_manager.go
> +	db, err := sql.Open("sqlserver", connectString)
Не нашел средств на открытие, только на запрос/пинг. Вроде в стандартной библиотеке нет такой возможности

2024-04-27 06:59 UTC, vitalyisaev2 requested changes

2024-04-27 06:59 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/sql_formatter.go
> +	return fmt.Sprintf("$%d", n+1)
я в другом месте увидел, что у тебя используются собаки, а не доллары

это нужно для того, чтобы исполнялись запросы вида `SELECT * FROM table WHERE col1 = первый_аргумент AND col2 < второй_аргумент`

так что если их синтаксис требует собак, здесь это тоже надо поправить

2024-04-27 06:59 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +	// Without that ClickHouse native driver would return invalid values for NULLABLE(bool) columns;
ClickHouse? 

напиши сюда комментарий, что ты скопипастил этот код с CH (хотя вообще-то я думал, что ты брал PostgreSQL),  и пока не знаешь, актуальна ли эта беда или нет

2024-04-27 06:59 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/utils/schema_provider.go
> +
лишняя строчка

2024-04-27 06:59 UTC, vitalyisaev2 commented on scripts/debug/config/client/ms_sql_server.local.txt
> +}
А в табличка маппинга типов будет обновлена в этом ревью?

2024-04-27 23:07 UTC, Glebbs commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +	// Without that ClickHouse native driver would return invalid values for NULLABLE(bool) columns;
Скопипастил, все верно, актуальность беды не знаю

2024-05-02 19:31 UTC, vitalyisaev2 requested changes

2024-05-02 19:31 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/connection_manager.go
> +	pingCtx, pingCtxCancel := context.WithTimeout(ctx, common.MustDurationFromString("5s"))
`pingCtx, pingCtxCancel := context.WithTimeout(ctx, 5 * duration.Second`

2024-05-02 19:31 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +			// ваш вызов преобразователя (appender)
комментарии на английском плз

2024-05-02 19:32 UTC, vitalyisaev2 requested changes

2024-05-02 19:32 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/connection_manager.go
> +	connectString := fmt.Sprintf("sqlserver://%s:%s@localhost:%d?database=%s",
захардкодил `localhost`

2024-05-03 19:31 UTC, Glebbs commented on app/server/datasource/rdbms/ms_sql_server/connection_manager.go
> +	pingCtx, pingCtxCancel := context.WithTimeout(ctx, common.MustDurationFromString("5s"))
time.Second?

2024-05-04 11:09 UTC, vitalyisaev2 requested changes

2024-05-04 11:09 UTC, vitalyisaev2 commented on .trunk/actions/trunk-cache-prune/2024-05-04-10-13-18.561.yaml
> +action_id: trunk-cache-prune
папочку `.trunk` стоит удалить

2024-05-04 11:09 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/connection_manager.go
> +	// }
если работает, раскомментируй

2024-05-04 11:09 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/ms_sql_server/type_mapper.go
> +			// TODO: add date & time processing
на данный момент отсюда тоже надо вернуть ошибку, что и в 114 строке

2024-05-04 11:22 UTC, vitalyisaev2 approved these changes

2024-05-04 11:24 UTC, merged