Support MySQL/MariaDB data sources
ydb-platform/fq-connector-go pull request #94
Opened 2024-04-26 15:02 UTC by mkls6

This PR adds basic implementation for MySQL/MariaDB RDBMS.

- [x] Support `varchar`, `string`, `blob`, `text` — all are mapped to clickhouse's `UTF8` type
- [x] Support `smallint` — `INT16`
- [x] Support `tinyint` (`bool` is an alias for `tinyint(1)`), either map to `Bool` or `INT8`/`UINT8`.
- [x] Support `mediumint`, `int` — `INT32`
- [x] Support `float`, `double` — `FLOAT32` and `FLOAT64` respectively
- [x] Handle multiple `ResultSets`
- [x] Support unsigned datatypes
- ~~Support `date`, `datetime`, `timestamp`~~ (will be done in a separate PR)
- [x] Fill information about type mappings in `docs/type_mapping_table.md`

2024-04-26 16:45 UTC, vitalyisaev2 requested changes

2024-04-26 16:45 UTC, vitalyisaev2 commented on api/common/data_source.pb.go
> +	EDataSourceKind_MS_SQL_SERVER                EDataSourceKind = 6
А можешь сделать ребейз? вроде как эти изменения уже есть в апстриме https://github.com/ydb-platform/fq-connector-go/blob/main/api/common/data_source.pb.go#L34

2024-04-26 16:45 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/data_source_factory.go
> +			SchemaProvider:    rdbms_utils.NewDefaultSchemaProvider(mysqlTypeMapper, mysql.GetQueryAndArgs),
сделай pls ребейз - в этой структуре появилось пятое поле, если не проинициализировать, то будет падать

2024-04-26 16:45 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/connection.go
> +	result, err := c.conn.Execute(query, args...)
Любопытно. То есть здесь не `conn.Query` или `conn.QueryContext`, а именно `Execute`? это прям так принято у них?  

У тебя нет ощущения, что это в большей степени подойдёт нам? https://github.com/go-mysql-org/go-mysql/blob/master/client/conn.go#L313

Ведь мы как раз должны стримить данные... У нас большие таблицы, и мы как раз не буферизуем вывод. Подход с коллбеком на строчку выглядит многообещающим

2024-04-26 18:00 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +}
Подход в их библиотеке, конечно, вызывает недоумение... Надеюсь, что та стримовая функция нам подойдёт больше, и здесь многое поменяется.

2024-04-26 18:01 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +			return err
врапни ошибку плз

2024-04-26 18:02 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +			mysql.MYSQL_TYPE_LONG_BLOB, mysql.MYSQL_TYPE_BLOB:
предположу, что `BLOB` логичнее приводить к `*[]byte`

2024-04-26 18:07 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +				tmp := new(string)
На мой взгляд, подобная аллокация внутри `Scan` выглядит как ошибка. По интерфейсу этой функции ведь видно, что она принимает по указателю объекты, в которые нужно произвести запись. Значит если кто-то прислал не те объекты, это нарушение контракта со стороны клиента функции. Если не удалось привести к строке, кинь панику - узнаем, что прислали, и так найдём больной зуб. 99% что ошибка где-то в маппинге типов.

2024-04-26 18:14 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +				*dest[i].(**int32) = tmp
`*dest[i]` должен быть уже проинициализирован внешним пользователем функции. Там непустой указатель должен лежать. Наиболее близким примером для тебя будет ClickHouse, посмотри как там инициализируется массив акцепторов: https://github.com/ydb-platform/fq-connector-go/blob/main/app/server/datasource/rdbms/clickhouse/type_mapper.go#L111-L235

Если мы будем аллоцировать акцепторы каждый раз при вызове `Scan`, мы взорвёмся по памяти, а затем и по cpu (из-за GC)

2024-04-26 18:17 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +	ids := make([]uint8, 0, len(fields))
можешь плиз добавить комментарий, uint8  у них используется для хранения идентификатора типа? а то немного необычно

2024-04-26 18:18 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +	case "varchar", "string", "longblob", "blob", "text":
уже выше писал, здесь повторюсь, что если блобы - это байтовые строки, тогда их надо смапить в Ydb String

2024-05-21 22:33 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection.go
> +	result, err := c.conn.Execute(query, args...)
Переписал на стриминг в 2425694

2024-05-21 22:47 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection_manager.go
> +	conn, err := client.ConnectWithDialer(ctx, proto, addr, user, password, db, dialer.DialContext)
Похоже, что контекст в библиотеке можно передать в клиентской части только при создании подключения через `ConnectWithDialer()` и `ConnectWithContext()` (в более новой версии, под капотом создаёт `net.Dialer` с переданным контекстом). После успешного подключения при выполнении непосредственно запросов к СУБД контексты не используются

2024-05-21 22:52 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/get_query_and_args.go
> +	args := []any{request.Table, request.GetDataSourceInstance().Database}
В MySQL [схема — это синоним БД](https://dev.mysql.com/doc/refman/8.3/en/glossary.html#glos_schema), поэтому в `information_schema` можно передавать название БД в качестве значения `table_schema`

2024-05-22 13:31 UTC, vitalyisaev2 requested changes

2024-05-22 13:31 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +	case "smallint", "tinyint", "bool":
Тут не соглашусь, поскольку BOOL в YDB имеет свой собственный тип. Я бы сделал отдельный case для этого.

2024-05-22 13:31 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +			appenders = append(appenders, makeAppender[[]byte, []byte, *array.BinaryBuilder](cc.Bytes(), nullable))
соответственно и тут я бы тоже обработал `Ydb.Type_BOOL`

2024-05-22 13:31 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +	*cast = nil
Поставь плз TODO расследовать это обнуление, оно кажется подозрительным

2024-05-22 13:31 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +	//nolint:forcetypeassert
это точно нужно? в функции выше этого нет

2024-05-22 13:31 UTC, vitalyisaev2 commented on go.mod
> +	github.com/pingcap/errors v0.11.5-0.20210425183316-da1aaba5fb63 // indirect
Сделай  даунгрейд плз до версии v0.11.5-0.20201126102027-b0a155152ca3

2024-05-22 13:31 UTC, vitalyisaev2 commented on go.mod
> +	github.com/siddontang/go-log v0.0.0-20180807004314-8d05993dda07 // indirect
А здесь подними плз до v0.0.0-20190221022429-1e957dd83bed

2024-05-22 13:31 UTC, vitalyisaev2 commented on tests/infra/datasource/mysql/tables.go
> +				"bool_column":         common.MakeOptionalType(common.MakePrimitiveType(Ydb.Type_INT16)),
здесь BOOL плз

2024-05-22 13:31 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +		nullable := true
В MySQL все типы nullable, поэтому можно упростить код и убрать все лишние ветки, связанные с non-nullable

2024-05-22 13:31 UTC, vitalyisaev2 commented on tests/infra/datasource/mysql/tables.go
> +				"mediumint_column":    common.MakePrimitiveType(Ydb.Type_INT32),
В MySQL всё по своей природе Nullable. Так что здесь везде optional'ы

2024-05-22 13:31 UTC, vitalyisaev2 commented on tests/main_test.go
> +func TestMYSQL(t *testing.T) {
`TestMySQL`

2024-05-22 23:30 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +		nullable := true
Убрал в 7249bf0

2024-05-22 23:30 UTC, mkls6 commented on tests/infra/datasource/mysql/tables.go
> +				"mediumint_column":    common.MakePrimitiveType(Ydb.Type_INT32),
Убрал в 7249bf0

2024-05-23 00:49 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +	next := <-r.nextReady
Сделано в b8be125

2024-05-23 00:58 UTC, mkls6 commented on go.mod
> +	github.com/pingcap/errors v0.11.5-0.20210425183316-da1aaba5fb63 // indirect
Готово: 8f89ce5

2024-05-23 00:59 UTC, mkls6 commented on go.mod
> +	github.com/siddontang/go-log v0.0.0-20180807004314-8d05993dda07 // indirect
Done: bb42e96

2024-05-23 01:04 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/get_query_and_args.go
> +	args := []any{request.Table, request.GetDataSourceInstance().Database}
Добавил коротенький комментарий: f30c851

2024-05-23 01:06 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection.go
> +			// In per-row handler copy entire row. The driver re-uses internal,
Да :)
fcd9efd

2024-05-23 17:32 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +	return false
Если ничего [не упустил](https://github.com/go-mysql-org/go-mysql/blob/v1.6.0/client/stmt.go#L47) [в коде библиотеки](https://github.com/go-mysql-org/go-mysql/blob/v1.6.0/client/resp.go#L308), то нет. В драйвере для `database/sql` `NextResultSet()` не реализован. Всё вычитывается в рамках одного `ResultSet`'а.

2024-05-23 17:35 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +	ids := make([]uint8, 0, len(fields))
Добавить могу, но уже неактуально, так как теперь там `MakeTransformer` использует только типы `YDB`

2024-05-23 17:39 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection.go
> +				r.result = result
Функцию убрал, так как, судя по коду, фактически она вызывается в нашем случае 1 раз: перед началом чтения первых столбцов. И да, если бы результат менялся, то была бы гонка :)

2024-05-23 17:41 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection.go
> +const rowBuffer = 512
Добавил параметром в 468a4c4

2024-05-23 18:02 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection_manager.go
> +}
Добавил опцию для подключения по TLS-протоколу, но пока без клиентских сертификатов

2024-05-23 18:38 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/type_mapper.go
> +	*cast = nil
TODO поставил и вообще в целом закомментировал, при тестировании проблем не заметил и вообще это было давно скопировано из реализации подключения к clickhouse. Здесь проблем не наблюдаю.

2024-05-23 18:40 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +	}
Так как теперь там везде Optional-типы и соответственно двойные указатели (за исключением случая с чтением метаинформации о таблице), то по сути часть логики ушла. Оставшееся переписал на type switch в 368d3ab.

2024-05-23 19:46 UTC, vitalyisaev2 requested changes

2024-05-23 19:46 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/connection_manager.go
> +		optionFuncs = append(optionFuncs, func(c *client.Conn) { c.UseSSL(false) })
`true`?

2024-05-23 19:46 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/connection.go
> +	rowBuffer uint64
`rowBufferCapacity`?

2024-05-23 19:46 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +		if columnName == COLUMN_TYPE_COLUMN && schema == METAINFO_SCHEMA_NAME {
Случайно не проверял, в MySQL точно только одна такая база (схема), на которую распространяется данное исключение? Если есть ссылка на документ или исходники, после которых ты пришёл к данному выводу, было бы круто тоже в комментарий добавить.

2024-05-23 19:46 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +		*dest = v
насколько я понимаю, одинарных пойнтеров у нас больше нет, всё nullable и в связи с этим везде двойные пойнтеры? поэтому этот кейс можно убрать

2024-05-23 19:46 UTC, vitalyisaev2 commented on app/server/datasource/rdbms/mysql/rows.go
> +		*dest = &v
Если ты ещё не устал от меня, можно предложу маленькую оптимизацию?  Сейчас у тебя `v` эскейпится на хип всегда, т. е. это равносильно аллокации новой переменной в дин. памяти.

В моём варианте аллокация будет происходить, только если в приёмнике был `nil` (если прочитали `NULL` в последний раз). Во всех остальных случаях будет переиспользоваться ранее аллоцированная память.

```
switch dest := dest.(type) {
	case **OUT:
               if *dest == nil {
                     *dest = new(OUT)
               }
		**dest = OUT(value.(IN))
       default:
                // бросание ошибки
```

В сущности, даже свитч можно убрать, поскольку у нас теперь, можно сказать, "по контракту" двойные пойнтеры. А если пришло что-то иное, то это ошибка программиста, и пусть будет паника.

2024-05-23 19:53 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection_manager.go
> +		optionFuncs = append(optionFuncs, func(c *client.Conn) { c.UseSSL(false) })
Это флажок для валидации хоста, false её выключает)

2024-05-23 19:53 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +		if columnName == COLUMN_TYPE_COLUMN && schema == METAINFO_SCHEMA_NAME {
Да, `information_schema` одна системная, добавлю в комментарий

2024-05-23 19:53 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection.go
> +	rowBuffer uint64
👌🏻

2024-05-23 19:55 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +		*dest = v
При чтении название колонок и типов из `information_schema` сюда прилетает `*string` :)

2024-05-23 19:59 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection.go
> +	rowBuffer uint64
cb60206

2024-05-23 20:11 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +		*dest = &v
Сделал по предложенному варианту (2029511)

2024-05-23 20:24 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/connection_manager.go
> +		optionFuncs = append(optionFuncs, func(c *client.Conn) { c.UseSSL(false) })
Поменял на `true` в 7bceff9

2024-05-23 20:24 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +		if columnName == COLUMN_TYPE_COLUMN && schema == METAINFO_SCHEMA_NAME {
Добавил описания в комментарий (5cda64b)

2024-05-23 20:29 UTC, mkls6 commented on app/server/datasource/rdbms/mysql/rows.go
> +		if columnName == COLUMN_TYPE_COLUMN && schema == METAINFO_SCHEMA_NAME {
Убрал исключение вообще в 6fcb7f4

2024-05-23 20:44 UTC, vitalyisaev2 approved these changes

2024-05-23 20:45 UTC, merged