YQ-3172: Подключение Greenplum к конвектору
ydb-platform/fq-connector-go pull request #98
Opened 2024-05-14 12:51 UTC by skywalker-jpg

2024-05-15 09:35 UTC, vitalyisaev2 requested changes

2024-05-15 09:35 UTC, vitalyisaev2 commented on api/common/data_source.pb.go
> +// 	protoc        v5.26.1
Мне немного страшно от такого мощного изменения версии `protoc`... Можешь поставить себе третью версию и регенерировать исходники?

2024-05-15 09:35 UTC, vitalyisaev2 commented on dockerfile
> +FROM ubuntu:22.04 AS builder
1. Заведи [здесь](https://github.com/ydb-platform/fq-connector-go/tree/main/tests/infra/datasource) папочку `greenplum` и положи свой Dockerfile в неё 
2. У нас есть `docker-compose` [файл](https://github.com/ydb-platform/fq-connector-go/blob/main/tests/infra/datasource/docker-compose.yaml), который используется для интеграционных тестов на Go. Надо дописать туда новую секцию, чтобы контейнер с `Greenplum` собирался (при необходимости) и поднимался при команде `make integration_test_env_run` https://github.com/ydb-platform/fq-connector-go/blob/main/Makefile#L25
3. Скрипты инициализации и сами тесты скопируй из папки `postgresql`. https://github.com/ydb-platform/fq-connector-go/tree/main/tests/infra/datasource/postgresql
4. Добавь функцию для запуска тестов на Greenplum сюда https://github.com/ydb-platform/fq-connector-go/blob/main/tests/main_test.go
5. `make integration_test` должна успешно прогонять тесты на Greenplum
6. Всё то же самое должно взлететь и в CI

2024-05-15 09:35 UTC, vitalyisaev2 commented on dockerfile
> +    [ -f 7.0.0.zip ] || wget https://github.com/greenplum-db/gpdb/archive/refs/tags/7.0.0.zip && \
А какие версии GP используются в нашем облаке в MDB?

2024-05-15 09:35 UTC, vitalyisaev2 commented on load_data.sql
> + ('alex_jones', 'alex@example.com', NOW());
Этот скрипт инициализации удаляй в пользу тех скриптов, что уже разработаны для PostgreSQL. Исходим из того, что всё должно беспроблемно перенестись из PG на GP. Если будут проблемы - будем каждую отдельно обсуждать

2024-05-15 09:35 UTC, vitalyisaev2 commented on scripts/debug/config/client/gp.local.txt
> +            password: ""
А почему нет пароля? Лучше сразу научись инициализировать GP так, чтобы для входа требовался пароль. Ведь даже в руководстве к MDB требуется пароль для подключения: https://yandex.cloud/ru/docs/managed-greenplum/operations/connect#go

2024-05-15 12:04 UTC, skywalker-jpg commented on api/common/data_source.pb.go
> +// 	protoc        v5.26.1
че то не очень получается((

2024-05-15 12:26 UTC, skywalker-jpg commented on dockerfile
> +FROM ubuntu:22.04 AS builder
3) а они подойдут? у меня же еще есть entrypoint.sh

2024-05-15 12:29 UTC, skywalker-jpg commented on dockerfile
> +    [ -f 7.0.0.zip ] || wget https://github.com/greenplum-db/gpdb/archive/refs/tags/7.0.0.zip && \
6.x+

2024-05-15 12:30 UTC, skywalker-jpg commented on dockerfile
> +    [ -f 7.0.0.zip ] || wget https://github.com/greenplum-db/gpdb/archive/refs/tags/7.0.0.zip && \
https://wiki.yandex-team.ru/cloud/support/howto/mdb/greenplum/

2024-05-15 13:00 UTC, vitalyisaev2 commented on dockerfile
> +FROM ubuntu:22.04 AS builder
entrypoint.sh относится к п.1. Он должен лежать рядом с Dockerfile

2024-05-15 13:00 UTC, vitalyisaev2 commented on api/common/data_source.pb.go
> +// 	protoc        v5.26.1
Поставил protoc нужной версии на доступную тебе Linux машину

2024-05-15 13:03 UTC, vitalyisaev2 commented on dockerfile
> +    [ -f 7.0.0.zip ] || wget https://github.com/greenplum-db/gpdb/archive/refs/tags/7.0.0.zip && \
В Облаке используются 6.22 и 6.25. Поэтому надо переделать образ так, чтобы ставилась одна из этих версий. Как вариант, ты можешь иметь два `Dockerflie` - один для версии 7, другой для версии 6, либо один `Dockerfile`, но параметризуемый через https://docs.docker.com/build/guide/build-args/ или как-то ещё. 

По умолчанию для тестов мы хотим запускать тот же GP, что работает и в Облаке.

2024-05-20 08:06 UTC, vitalyisaev2 requested changes

2024-05-20 08:06 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +}
Критерием истины для данной функции должен быть юнит-тест с несколькими тест-кейсами.

2024-05-21 09:14 UTC, vitalyisaev2 requested changes

2024-05-23 10:20 UTC, vitalyisaev2 requested changes

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +type Records struct {
1. не делай типы экспортируемыми, если не планируешь их использовать за пределами функции. То же относится и к полям структуры.
2. я бы назвал этот тип `tableRow` или `row`, если есть идеи получше - предлагай

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +			log.Panic("UNSUPPORTED TYPE:", col)
лучше возвращать ошибку, но поскольку мы в тестах, можно просто `panic`

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +func sortTableByID(table arrow.Record) arrow.Record {
отключи funlen для этой функции

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +		switch col := table.Column(colIdx).(type) {
Отсортируй кейсы в этом свитче, чтобы всё было красиво - сначало инты, потом беззнаковые инты, потом флоаты и т. п.

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +				}
сделай шаблонную функцию для добавления значения в билдер. на это больно смотреть

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +				log.Panic("UNSUPPORTED TYPE", builder)
просто паника

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching.go
> +	}
defer в цикле считается плохим тоном

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/matching_test.go
> +func int32Ptr(i int32) *int32 {
пользуйся `ptr.Int32` https://github.com/ydb-platform/fq-connector-go/blob/main/library/go/ptr/ptr.go#L15

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/postgresql/tables.go
> +						ptr.Uint16(0),
почему?

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/ydb/init/01_basic.sh
> +        id Optional<Int32>,
ID должен быть не Optional

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/ydb/tables.go
> +				"id":               common.MakeOptionalType(common.MakePrimitiveType(Ydb.Type_INT32)),
здесь простой тип

2024-05-23 10:20 UTC, vitalyisaev2 commented on tests/infra/datasource/ydb/tables.go
> +					"id":            []*int32{ptr.Int32(1), ptr.Int32(2)},
здесь тоже

2024-05-23 12:16 UTC, skywalker-jpg commented on tests/infra/datasource/matching.go
> +	}
Почему?

2024-05-23 14:21 UTC, skywalker-jpg commented on tests/infra/datasource/postgresql/tables.go
> +						ptr.Uint16(0),
какой-то старый коммит, он уже перетерся

2024-05-23 18:46 UTC, vitalyisaev2 requested changes

2024-05-23 18:46 UTC, vitalyisaev2 commented on tests/infra/datasource/postgresql/tables.go
> +						ptr.Uint16(0),
Нет, тут что-то не то. Здесь был `nil`: https://github.com/ydb-platform/fq-connector-go/blob/main/tests/infra/datasource/postgresql/tables.go#L217 потому что в исходной таблице была дата, которая выходит за пределы диапазона: https://github.com/ydb-platform/fq-connector-go/blob/main/tests/infra/datasource/postgresql/init/init_db.sh#L64

По какой причине `nil` здесь поменялся на указатель на 0?

2024-05-23 18:46 UTC, vitalyisaev2 commented on tests/infra/datasource/ydb/tables.go
> +					"id":            []*int32{ptr.Int32(1), ptr.Int32(2)},
Ну ты же сам объявил `id` как `"id":               common.MakePrimitiveType(Ydb.Type_INT32),` - примитивный, а не опциональный тип. Так почему же здесь пойнтеры?

2024-05-23 18:46 UTC, vitalyisaev2 commented on tests/infra/datasource/ydb/tables.go
> +						*ptr.Uint64(0),
Замечание, аналогичное предыдущему. Здесь должен быть `nil`: https://github.com/ydb-platform/fq-connector-go/blob/main/tests/infra/datasource/ydb/init/01_basic.sh#L74. Никакого нуля тут быть не может.

2024-05-23 18:46 UTC, vitalyisaev2 commented on tests/infra/datasource/greenplum/init/entrypoint.sh
> +sleep 100
Ээ... поясни плз, что тут происходит? зачем такой гигантский слип? и что происходит потом - база грохается что ли?

2024-05-23 18:46 UTC, vitalyisaev2 commented on tests/infra/datasource/docker-compose.yaml
> +      - "5432:5432"
просто `- '5432'` (см. контейнер с PostgreSQL)

2024-05-23 18:46 UTC, vitalyisaev2 commented on tests/infra/datasource/docker-compose.yaml
> +    environment:
Убери из environment все параметры, которые не работают. Вот пароль же захардкожен у тебя,  да и юзер, какжется, тоже? насчёт базы  не знаю, глубоко не копал, но судя по тому, как устроен образ - она тоже хардкодится в образ.

2024-05-23 18:54 UTC, skywalker-jpg commented on tests/infra/datasource/ydb/tables.go
> +					"id":            []*int32{ptr.Int32(1), ptr.Int32(2)},
Если говорить честно, то без них он на тип данных жалуется, а-ля хотел []int32, а пришло []*int32

2024-05-23 19:05 UTC, skywalker-jpg commented on tests/infra/datasource/greenplum/init/entrypoint.sh
> +sleep 100
осталось от тестов. Удаляю

2024-05-23 20:33 UTC, skywalker-jpg commented on tests/infra/datasource/ydb/tables.go
> +						*ptr.Uint64(0),
Я честно не понимаю почему оно без этого работать не хочет.  Я честно 4 часа сидел исправить, но у меня е получилось. Не хочет оно с nil

2024-05-24 10:58 UTC, vitalyisaev2 commented on tests/infra/datasource/ydb/tables.go
> +						*ptr.Uint64(0),
Я пофиксил это в [2969009](https://github.com/ydb-platform/fq-connector-go/pull/98/commits/2969009c6e7b567d9499ae7254c7f83244194a32)

2024-05-24 11:58 UTC, vitalyisaev2 approved these changes

2024-05-24 11:58 UTC, merged